### ISSUE TITLE
TST: utils/extract unit tests that are failing

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatModels#22] opened 2020-01-30 18:41 UTC
Tests that still fail in test_utils_extract.py:

* [x] TestUtilsExtractModObs::test_success
* [x] TestUtilsExtractModObs::test_bad_kwarg_input[method-not_a_method-interpn only understands the methods]
* [x] TestUtilsExtractModObs::test_bad_kwarg_input[sel_name-bad_val0-No model data keys to interpolate]

**Expected behavior**
These tests should pass.  I think they need a better model instrument to work (not the same time cadence as the data instrument).

**Comment by jklenzing** [comment] 2020-01-30 18:57
Found the cause of test_success
https://github.com/pysat/pysatModels/blob/471dfca81e992c2f0bde3519b6197feaf7e01124/pysatModelUtils/tests/test_utils_extract.py#L114

 Should be `self.model.data.data_vars.keys():`, as model.data is the `Dataset` object.

**Comment by jklenzing** [comment] 2020-01-30 19:00
I suspect that the route cause of the rest is a change in syntax needed since we are now using the pysat_testing2d_xarray object.

**Comment by jklenzing** [comment] 2020-01-30 19:33
In the `"method", "not_a_method"` bad kwarg test, is the error message generated by scipy? or the local package?  Can't find where this error message is generated.

**Comment by jklenzing** [comment] 2020-01-30 19:53
For `test_bad_kwarg_input[sel_name-bad_val0`, these are the lines that are tested:
https://github.com/pysat/pysatModels/blob/471dfca81e992c2f0bde3519b6197feaf7e01124/pysatModelUtils/utils/extract.py#L601-L605
However, running with `sel_name='Epoch'` in the test, Epoch is not part of the model object.  I suspect that the intention of the test can be satisfied by using `sel_name='slt'` instead.  This is compatible with the new xarray test object. Is this correct?

**Comment by aburrell** [comment] 2020-01-30 20:18
> n the "method", "not_a_method" bad kwarg test, is the error message generated by scipy? or the local package? Can't find where this error message is generated.

It's generated by the scipy interpolation routine.

**Comment by jklenzing** [comment] 2020-01-30 21:01
Close to tracking down the scipy related test failure.  
https://github.com/pysat/pysatModels/blob/471dfca81e992c2f0bde3519b6197feaf7e01124/pysatModelUtils/utils/extract.py#L684-L691
Essentially, `get_coords` (as generated at Line 688) is eternally false for the test instrument and model as defined, `interpn` is never called, and the error is never triggered.  Haven't tracked down the root yet.

https://github.com/pysat/pysatModels/blob/471dfca81e992c2f0bde3519b6197feaf7e01124/pysatModelUtils/utils/extract.py#L626-L637
Also, for a test instrument with only one time stamp, `min_del` results in a nan value, which means the if statement at line 637 is never triggered.  Running the test instrument with `sat_id='2'` or greater fixes this part of the problem, but the problems in Lines 684-691 remain)

**Comment by aburrell** [comment] 2020-01-30 21:03
> Essentially, get_coords (as generated at Line 688) is eternally false for the test instrument and model as defined, interpn is never called, and the error is never triggered. Haven't tracked down the root yet.

The root is that the model times need to be at a slower cadence than the instrument times.

**Comment by jklenzing** [comment] 2020-01-30 21:07
Trying this with the 15 minute cadence version of the model.  That may be too slow, though.

**Comment by jklenzing** [comment] 2020-04-01 22:27
Closing with merge of #29.

**Closed by jklenzing** 2020-04-01 22:27 UTC
Labels: bug
